import React from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import { useLabStore } from '../store/useLabStore';
import { getColors } from '../styles/colors';
import { fontScale, resolveFontFamily } from '../styles/design';

export default function CriticalAlertsScreen({navigation}:any){
 const enabled=useLabStore(s=>s.criticalAlertsEnabled); const setEnabled=useLabStore(s=>s.setCriticalAlertsEnabled); const alerts=useLabStore(s=>s.criticalAlerts); const clear=useLabStore(s=>s.clearCriticalAlerts); const dark=useLabStore(s=>s.darkMode); const theme=useLabStore(s=>s.theme); const family=useLabStore(s=>s.fontFamily); const size=useLabStore(s=>s.fontSize); const c=getColors(dark,theme), f=resolveFontFamily(family), sc=fontScale(size), styles=createStyles(c,f,sc);
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()} style={styles.back}><Text style={styles.backText}>‹</Text></TouchableOpacity><View><Text style={styles.kicker}>السلامة والمتابعة</Text><Text style={styles.title}>التنبيهات الحرجة</Text></View></View><View style={styles.setting}><View style={{flex:1}}><Text style={styles.settingTitle}>تفعيل التنبيهات</Text><Text style={styles.help}>عند إدخال قيمة حرجة معرفة في دليل الفحوصات سيظهر تنبيه، وتُحفظ العملية هنا.</Text></View><Switch value={enabled} onValueChange={setEnabled}/></View><View style={styles.info}><Text style={styles.infoTitle}>ملاحظة</Text><Text style={styles.help}>التطبيق لا يضع قيمًا حرجة طبية تلقائيًا. يجب تعريفها من «دليل الفحوصات والقيم» حسب مرجع مختبرك.</Text></View><View style={styles.listHeader}><Text style={styles.sectionTitle}>سجل التنبيهات ({alerts.length})</Text>{alerts.length>0&&<TouchableOpacity onPress={()=>Alert.alert('مسح السجل','هل تريد مسح سجل التنبيهات؟',[{text:'إلغاء',style:'cancel'},{text:'مسح',style:'destructive',onPress:clear}])}><Text style={styles.clear}>مسح السجل</Text></TouchableOpacity>}</View>{alerts.map(a=><View key={a.id} style={styles.card}><Text style={styles.alertTitle}>⚠ {a.testName}</Text><Text style={styles.row}>المريض: {a.patientName}</Text><Text style={styles.row}>النتيجة: {a.value}</Text><Text style={styles.row}>القاعدة الحرجة: {a.rule}</Text><Text style={styles.time}>{new Date(a.timestamp).toLocaleString()}</Text></View>)}{!alerts.length&&<View style={styles.empty}><Text style={styles.emptyTitle}>لا توجد تنبيهات حرجة</Text><Text style={styles.help}>ستظهر هنا بعد تسجيل نتائج حرجة.</Text></View>}</ScrollView></SafeAreaView>;
}
const createStyles=(c:any,f:string,s:number)=>StyleSheet.create({container:{flex:1,backgroundColor:c.paper},content:{paddingBottom:40},header:{backgroundColor:c.headerBg,padding:18,flexDirection:'row',alignItems:'center'},back:{width:40,height:40,borderRadius:12,backgroundColor:'rgba(255,255,255,.12)',alignItems:'center',justifyContent:'center',marginRight:12},backText:{color:'#fff',fontSize:30},kicker:{color:'#B7E8E2',fontFamily:f,fontSize:11*s,fontWeight:'700'},title:{color:'#fff',fontFamily:f,fontSize:22*s,fontWeight:'900'},setting:{margin:14,padding:16,borderRadius:16,borderWidth:1,borderColor:c.line,backgroundColor:c.panel,flexDirection:'row',alignItems:'center'},settingTitle:{color:c.ink,fontFamily:f,fontSize:14*s,fontWeight:'900'},help:{color:c.inkSub,fontFamily:f,fontSize:11*s,lineHeight:18,marginTop:4},info:{marginHorizontal:14,padding:14,borderRadius:15,backgroundColor:c.sealLight,borderWidth:1,borderColor:c.line},infoTitle:{color:c.ink,fontFamily:f,fontSize:13*s,fontWeight:'900'},listHeader:{margin:16,marginBottom:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectionTitle:{color:c.ink,fontFamily:f,fontSize:16*s,fontWeight:'900'},clear:{color:c.danger,fontFamily:f,fontSize:11*s,fontWeight:'900'},card:{marginHorizontal:14,marginTop:8,padding:14,borderRadius:15,borderWidth:1,borderColor:c.danger,backgroundColor:c.panel},alertTitle:{color:c.danger,fontFamily:f,fontSize:13*s,fontWeight:'900'},row:{color:c.ink,fontFamily:f,fontSize:11*s,marginTop:5},time:{color:c.inkSub,fontFamily:f,fontSize:9*s,marginTop:8},empty:{margin:14,padding:28,borderRadius:16,borderWidth:1,borderColor:c.line,backgroundColor:c.panel,alignItems:'center'},emptyTitle:{color:c.ink,fontFamily:f,fontSize:15*s,fontWeight:'900'}});
