import React, { useMemo, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLabStore } from '../store/useLabStore';
import { getColors } from '../styles/colors';
import { resolveFontFamily, fontScale } from '../styles/design';
import { getStats, exportStatsPdf, printStats } from '../services/exportService';

export default function StatsScreen(){
 const patients=useLabStore(s=>s.patients);const settings=useLabStore(s=>s.settings);const dark=useLabStore(s=>s.darkMode);const theme=useLabStore(s=>s.theme);const fam=useLabStore(s=>s.fontFamily);const fs=useLabStore(s=>s.fontSize);
 const c=getColors(dark,theme);const f=resolveFontFamily(fam);const sc=fontScale(fs);const styles=createStyles(c,f,sc);const stats=useMemo(()=>getStats(patients),[patients]);const [busy,setBusy]=useState(false);
 const run=async(fn:()=>Promise<any>,msg:string)=>{try{setBusy(true);await fn();Alert.alert('تم',msg)}catch(e:any){Alert.alert('خطأ',e?.message||'تعذر تنفيذ العملية')}finally{setBusy(false)}};
 const totalTests=stats.sections.reduce((n,s)=>n+s.count,0);
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}>
  <View style={styles.header}><Text style={styles.kicker}>لوحة البيانات</Text><Text style={styles.title}>الإحصائيات</Text><Text style={styles.subtitle}>ملخص قابل للطباعة والتصدير</Text></View>
  <View style={styles.summaryGrid}><Metric label="إجمالي المرضى" value={stats.total} styles={styles}/><Metric label="مرضى اليوم" value={stats.today} styles={styles}/><Metric label="ذكور" value={stats.males} styles={styles}/><Metric label="إناث" value={stats.females} styles={styles}/></View>
  <View style={styles.section}><Text style={styles.sectionTitle}>توزيع الأقسام</Text>{stats.sections.map(s=><View key={s.key} style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{s.name}</Text><Text style={styles.rowSub}>{s.tests.filter(t=>t.count>0).length} فحص مسجل</Text></View><Text style={styles.rowValue}>{s.count}</Text></View>)}</View>
  <View style={styles.section}><Text style={styles.sectionTitle}>مؤشرات سريعة</Text><View style={styles.info}><Text style={styles.infoLabel}>إجمالي سجلات الأقسام</Text><Text style={styles.infoValue}>{totalTests}</Text></View><View style={styles.info}><Text style={styles.infoLabel}>سجلات تحتوي ملاحظات</Text><Text style={styles.infoValue}>{patients.filter(p=>!!p.notes?.trim()).length}</Text></View></View>
  <View style={styles.actions}><TouchableOpacity disabled={busy} onPress={()=>run(()=>exportStatsPdf(stats,settings,settings.printSettings||{}),'تم إنشاء PDF الإحصائيات')} style={styles.primary}><Text style={styles.primaryText}>حفظ ومشاركة PDF</Text></TouchableOpacity><TouchableOpacity disabled={busy} onPress={()=>run(()=>printStats(stats,settings,settings.printSettings||{}),'تم إرسال الإحصائيات للطباعة')} style={styles.secondary}><Text style={styles.secondaryText}>طباعة الإحصائيات</Text></TouchableOpacity></View>
 </ScrollView>{busy&&<View style={styles.busy}><Text style={styles.busyText}>جارٍ تجهيز الملف…</Text></View>}</SafeAreaView>
}
function Metric({label,value,styles}:{label:string;value:any;styles:any}){return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}
const createStyles=(c:any,f:string,s:number)=>StyleSheet.create({container:{flex:1,backgroundColor:c.paper},content:{paddingBottom:38},header:{backgroundColor:c.headerBg,padding:20},kicker:{color:'#B7E8E2',fontSize:11*s,fontFamily:f,fontWeight:'700'},title:{color:'#fff',fontSize:25*s,fontWeight:'900',fontFamily:f,marginTop:2},subtitle:{color:'#D7EFEC',fontSize:11*s,fontFamily:f,marginTop:4},summaryGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,padding:14},metric:{width:'48%',backgroundColor:c.panel,borderWidth:1,borderColor:c.line,borderRadius:16,padding:15},metricValue:{color:c.navy,fontSize:23*s,fontWeight:'900',fontFamily:f},metricLabel:{color:c.inkSub,fontSize:11*s,fontFamily:f,marginTop:4},section:{marginHorizontal:14,marginBottom:12,padding:16,borderRadius:17,backgroundColor:c.panel,borderWidth:1,borderColor:c.line},sectionTitle:{color:c.ink,fontSize:15*s,fontWeight:'900',fontFamily:f,marginBottom:10},row:{flexDirection:'row',alignItems:'center',paddingVertical:11,borderBottomWidth:1,borderBottomColor:c.line},rowTitle:{color:c.ink,fontSize:13*s,fontWeight:'800',fontFamily:f},rowSub:{color:c.inkSub,fontSize:10*s,fontFamily:f,marginTop:2},rowValue:{color:c.navy,fontSize:19*s,fontWeight:'900',fontFamily:f},info:{flexDirection:'row',justifyContent:'space-between',paddingVertical:10,borderBottomWidth:1,borderBottomColor:c.line},infoLabel:{color:c.inkSub,fontFamily:f,fontSize:11*s},infoValue:{color:c.ink,fontFamily:f,fontSize:14*s,fontWeight:'900'},actions:{padding:14,gap:9},primary:{minHeight:52,borderRadius:15,backgroundColor:c.navy,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontFamily:f,fontSize:14*s,fontWeight:'900'},secondary:{minHeight:50,borderRadius:15,borderWidth:1,borderColor:c.navy,alignItems:'center',justifyContent:'center'},secondaryText:{color:c.navy,fontFamily:f,fontSize:13*s,fontWeight:'900'},busy:{position:'absolute',left:20,right:20,bottom:20,padding:14,borderRadius:14,backgroundColor:c.headerBg,alignItems:'center'},busyText:{color:'#fff',fontFamily:f,fontWeight:'800'}});
