import React, { useMemo, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLabStore } from '../store/useLabStore';
import { SECTION_KEYS, TEST_SECTIONS, SectionKey } from '../utils/constants';
import { getColors } from '../styles/colors';
import { fontScale, resolveFontFamily } from '../styles/design';

export default function TestPricesScreen({ navigation }: any) {
  const catalog=useLabStore(s=>s.testCatalog); const prices=useLabStore(s=>s.testPrices); const setPrice=useLabStore(s=>s.setTestPrice); const dark=useLabStore(s=>s.darkMode); const theme=useLabStore(s=>s.theme); const family=useLabStore(s=>s.fontFamily); const size=useLabStore(s=>s.fontSize);
  const c=getColors(dark,theme), f=resolveFontFamily(family), sc=fontScale(size), styles=createStyles(c,f,sc); const [q,setQ]=useState(''); const [section,setSection]=useState<'all'|SectionKey>('all'); const [draft,setDraft]=useState<Record<string,string>>({}); const [saving,setSaving]=useState<string|null>(null);
  const list=useMemo(()=>catalog.filter(t=>(!q.trim()||`${t.name} ${t.abbreviation} ${t.key}`.toLowerCase().includes(q.trim().toLowerCase()))&&(section==='all'||t.section===section)),[catalog,q,section]);
  const save=async(key:string)=>{try{setSaving(key);const n=Math.max(0,Number((draft[key]??String(prices[key]??0)).replace(',','.'))||0);await setPrice(key,n);setDraft(v=>({...v,[key]:String(n)}));}catch(e:any){Alert.alert('خطأ',e?.message||'تعذر حفظ السعر.')}finally{setSaving(null)}};
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()} style={styles.back}><Text style={styles.backText}>‹</Text></TouchableOpacity><View><Text style={styles.kicker}>إدارة المختبر</Text><Text style={styles.title}>أسعار الفحوصات</Text></View></View><TextInput value={q} onChangeText={setQ} placeholder="ابحث عن فحص" placeholderTextColor={c.inkSub} style={styles.search}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><Filter title="الكل" active={section==='all'} onPress={()=>setSection('all')} styles={styles}/>{SECTION_KEYS.map(k=><Filter key={k} title={TEST_SECTIONS[k].label} active={section===k} onPress={()=>setSection(k)} styles={styles}/>)}</ScrollView>{list.map(t=>{const value=draft[t.key]??String(prices[t.key]??t.price??0);return <View key={t.id} style={styles.row}><View style={{flex:1}}><Text style={styles.name}>{t.name}</Text><Text style={styles.meta}>{t.abbreviation} • {TEST_SECTIONS[t.section]?.label}</Text></View><TextInput value={value} onChangeText={v=>setDraft(d=>({...d,[t.key]:v}))} keyboardType="decimal-pad" style={styles.priceInput}/><TouchableOpacity onPress={()=>save(t.key)} disabled={saving===t.key} style={styles.save}><Text style={styles.saveText}>{saving===t.key?'…':'حفظ'}</Text></TouchableOpacity></View>})}</ScrollView></SafeAreaView>;
}
function Filter({title,active,onPress,styles}:any){return <TouchableOpacity onPress={onPress} style={[styles.filter,active&&styles.active]}><Text style={[styles.filterText,active&&styles.white]}>{title}</Text></TouchableOpacity>}
const createStyles=(c:any,f:string,s:number)=>StyleSheet.create({container:{flex:1,backgroundColor:c.paper},content:{paddingBottom:40},header:{backgroundColor:c.headerBg,padding:18,flexDirection:'row',alignItems:'center'},back:{width:40,height:40,borderRadius:12,backgroundColor:'rgba(255,255,255,.12)',alignItems:'center',justifyContent:'center',marginRight:12},backText:{color:'#fff',fontSize:30},kicker:{color:'#B7E8E2',fontSize:11*s,fontFamily:f,fontWeight:'700'},title:{color:'#fff',fontSize:22*s,fontFamily:f,fontWeight:'900'},search:{margin:14,minHeight:48,borderRadius:13,borderWidth:1,borderColor:c.line,backgroundColor:c.panel,color:c.ink,paddingHorizontal:12,textAlign:'right',fontFamily:f},filters:{paddingHorizontal:14,gap:8,marginBottom:10},filter:{paddingHorizontal:14,paddingVertical:9,borderRadius:18,borderWidth:1,borderColor:c.line,backgroundColor:c.panel},active:{backgroundColor:c.navy,borderColor:c.navy},filterText:{color:c.inkSub,fontFamily:f,fontSize:11*s,fontWeight:'800'},white:{color:'#fff'},row:{marginHorizontal:14,marginTop:8,padding:12,borderRadius:14,borderWidth:1,borderColor:c.line,backgroundColor:c.panel,flexDirection:'row',alignItems:'center',gap:8},name:{color:c.ink,fontFamily:f,fontSize:12*s,fontWeight:'900'},meta:{color:c.inkSub,fontFamily:f,fontSize:9.5*s,marginTop:3},priceInput:{width:92,minHeight:42,borderRadius:10,borderWidth:1,borderColor:c.line,backgroundColor:c.paper,color:c.ink,textAlign:'center',fontFamily:f,fontWeight:'900'},save:{minWidth:54,minHeight:42,borderRadius:10,backgroundColor:c.navy,alignItems:'center',justifyContent:'center'},saveText:{color:'#fff',fontFamily:f,fontWeight:'900',fontSize:10*s}});
